/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation {
	float operator1;
	float operator2;
	char operator;
};
typedef struct operation operation;

struct operation_res {
	int errnum;
	union {
		float result;
	} operation_res_u;
};
typedef struct operation_res operation_res;

#define CALCULATOR 0x20000001
#define SIMPLEOPERATION 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPERATE 1
extern  float * operate_1(operation , CLIENT *);
extern  float * operate_1_svc(operation , struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPERATE 1
extern  float * operate_1();
extern  float * operate_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation (XDR *, operation*);
extern  bool_t xdr_operation_res (XDR *, operation_res*);

#else /* K&R C */
extern bool_t xdr_operation ();
extern bool_t xdr_operation_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
