/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
operate_1_svc(operation arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

resultVect *
operate_vector_1_svc(operationVector arg1,  struct svc_req *rqstp)
{
	static resultVect  result;

	result.vec[0] = 1;

	return &result;
}
