/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calculator_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	operation operate_1_arg1;
	resultVect  *result_2;
	operationVector operate_vector_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATOR, VEC_OPERATION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = operate_1(operate_1_arg1, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = operate_vector_1(operate_vector_1_arg1, clnt);
	if (result_2 == (resultVect *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%f", result_2->vec[0]);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculator_1 (host);
exit (0);
}
