/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "calc.h"

float *
operate_1_svc(operation arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
operate_2_svc(operation arg1,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vec_result suma(vec_operation op)
{
	static vec_result result;
	for (int i = 0; i < MAX; ++i)
	{
		result.vec[i] = op.vec1[i] + op.vec2[i];
	}
	return result;
	
}

vec_result resta(vec_operation op)
{
	static vec_result result;
	for (int i = 0; i < MAX; ++i)
	{
		result.vec[i] = op.vec1[i] - op.vec2[i];
	}
	return result;
	
}

vec_result *
operate_vector_2_svc(vec_operation arg1,  struct svc_req *rqstp)
{
	static vec_result  result;
	
    FILE *f;
	f = fopen("/dev/tty", "w");

    fprintf(f, "%d", arg1.vec1[0]);
    fclose(f);

	result = suma(arg1);

    fprintf(f, "%d", result.vec[0]);
    fclose(f);

	return &result;
}
