/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_operation (XDR *xdrs, operation *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->operator1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->operator2))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->operator))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vec_operation (XDR *xdrs, vec_operation *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vec1, MAX,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->vec2, MAX,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->operator, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vec_result (XDR *xdrs, vec_result *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->vec, MAX,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
