/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX 3

struct operation {
	float operator1;
	float operator2;
	char operator;
};
typedef struct operation operation;

struct vec_operation {
	float vec1[MAX];
	float vec2[MAX];
	char *operator;
};
typedef struct vec_operation vec_operation;

struct vec_result {
	float vec[MAX];
};
typedef struct vec_result vec_result;

#define CALCULATOR 0x20000001
#define SIMPLEOPERATION 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPERATE 1
extern  float * operate_1(operation , CLIENT *);
extern  float * operate_1_svc(operation , struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPERATE 1
extern  float * operate_1();
extern  float * operate_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */
#define SIMP_VEC_OPERATION 2

#if defined(__STDC__) || defined(__cplusplus)
extern  float * operate_2(operation , CLIENT *);
extern  float * operate_2_svc(operation , struct svc_req *);
#define OPERATE_VECTOR 2
extern  vec_result * operate_vector_2(vec_operation , CLIENT *);
extern  vec_result * operate_vector_2_svc(vec_operation , struct svc_req *);
extern int calculator_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  float * operate_2();
extern  float * operate_2_svc();
#define OPERATE_VECTOR 2
extern  vec_result * operate_vector_2();
extern  vec_result * operate_vector_2_svc();
extern int calculator_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation (XDR *, operation*);
extern  bool_t xdr_vec_operation (XDR *, vec_operation*);
extern  bool_t xdr_vec_result (XDR *, vec_result*);

#else /* K&R C */
extern bool_t xdr_operation ();
extern bool_t xdr_vec_operation ();
extern bool_t xdr_vec_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
