/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

Result *
operate_1_svc(operation arg1,  struct svc_req *rqstp)
{
	static Result  result;

	switch (arg1.operator)
	{
	case '+':
		result.resultado = arg1.operator1 + arg1.operator2;
		break;

	case '-':
		result.resultado = arg1.operator1 - arg1.operator2;
		break;

	case '*' || 'x':
		result.resultado = arg1.operator1 * arg1.operator2;
		break;

	case '/':
		result.resultado = arg1.operator1 / arg1.operator2;
		break;

	case '^':
		result.resultado = pow(arg1.operator1, arg1.operator2);
		break;

	case 'q':
		result.resultado = sqrt(arg1.operator2);
		break;

	case 's':
		result.resultado = sin(arg1.operator2);
		break;

	case 'c':
		result.resultado = cos(arg1.operator2);
		break;

	case 't':
		result.resultado = tan(arg1.operator2);
		break;
	
	case 'l':
		result.resultado = log(arg1.operator2);
		break;
		
	default:
		break;
	}
	return &result;
}

Result suma(operationVector operation)
{
	Result result;
	for (int i = 0; i < 3; ++i)
	{
		result.vec[i] = operation.vec1[i] + operation.vec2[i];
	}
	return result;
}

Result resta(operationVector operation)
{
	Result result;
	for (int i = 0; i < 3; ++i)
	{
		result.vec[i] = operation.vec1[i] - operation.vec2[i];
	}
	return result;
}

Result prodEscalar(operationVector operation)
{
	Result result;
	for (int i = 0; i < 3; ++i)
	{
		result.vec[i] = operation.vec1[0] * operation.vec2[i];
	}
	return result;
}

Result prodVectorial(operationVector operation)
{
	Result result;
	result.vec[0] = operation.vec1[1] * operation.vec2[2] - operation.vec1[2] * operation.vec2[1];
	result.vec[1] = operation.vec1[2] * operation.vec2[0] - operation.vec1[0] * operation.vec2[2];
	result.vec[2] = operation.vec1[0] * operation.vec2[1] - operation.vec1[1] * operation.vec2[0];
	return result;
}

Result *
operate_vector_1_svc(operationVector arg1,  struct svc_req *rqstp)
{
	static Result  result;

	switch (arg1.operator)
	{
	case '+':
		result = suma(arg1);
		break;
	
	case '-':
		result = resta(arg1);
		break;

	case '·':
		result = prodEscalar(arg1);
		break;
	
	case 'x':
		result = prodVectorial(arg1);
		break;

	default:
		break;
	}

	return &result;
}
